include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - lib/generated/**

  errors:
    missing_return: error
    parameter_assignments: error
    missing_required_param: error